name: Awesome action
description: Run an awesome action
inputs:
  template-input-path:
    description: 'path to the payload template to fix'
    required: true
  template-output-path:
    description: 'path of the fixed template'
    required: true
  replacements:
    description: 'replacements to perform'
    required: true
outputs:
  template-output-path:
    description: 'path of the fixed template'
runs:
  using: node16
  main: dist/index.js